-- ********************************
-- *** BANCO DE DADOS: CARTORIO ***
-- ********************************
--
--------------------------------------------------
-- COMANDOS DDL DROP
--------------------------------------------------
--
-- DROP TYPES
DROP TYPE "TP_DESCONTO" FORCE; 
DROP TYPE "TP_ENDERECO" FORCE;  
DROP TYPE "TP_FONE" FORCE;
DROP TYPE "TP_FONES" FORCE;
DROP TYPE "TP_LIVRO" FORCE;
DROP TYPE "TP_PESSOA" FORCE;
DROP TYPE "TP_SERVICO" FORCE;
DROP TYPE "TP_TIPOFUNCIONARIO" FORCE;
DROP TYPE "TP_TIPOSERVICO" FORCE;
DROP TYPE "TP_ATENDIMENTO" FORCE; 
DROP TYPE "TP_CLIENTE" FORCE; 
DROP TYPE "TP_FISICA" FORCE;  
DROP TYPE "TP_FUNCIONARIO" FORCE;
DROP TYPE "TP_GRATIFICACAO" FORCE;
DROP TYPE "TP_JURIDICA" FORCE;
DROP TYPE "TP_PODERECEBER" FORCE;
DROP TYPE "TP_REGISTRO" FORCE;
DROP TYPE "TP_SERVICODOATENDIMENTO" FORCE;
DROP TYPE "TP_LOGATENDIMENTO" FORCE;
DROP TYPE "TP_TUPLASERVICODOATENDIMENTO" FORCE;
-- DROP TABELAS
DROP TABLE "TB_DESCONTO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_LIVRO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_SERVICO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_TIPOFUNCIONARIO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_TIPOSERVICO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_ATENDIMENTO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_CLIENTE" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_FISICA" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_FUNCIONARIO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_JURIDICA" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_REGISTRO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_SERVICODOATENDIMENTO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_LOGATENDIMENTO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TB_LOGSERVICODOATENDIMENTO" CASCADE CONSTRAINTS PURGE;
-- DROP SEQUENCES
DROP SEQUENCE SEQ_TB_LIVRO;
DROP SEQUENCE SEQ_TB_DESCONTO;
DROP SEQUENCE SEQ_TB_TIPOSERVICO;
DROP SEQUENCE SEQ_TB_SERVICO;
DROP SEQUENCE SEQ_TB_TIPOFUNCIONARIO;
DROP SEQUENCE SEQ_TB_FUNCIONARIO;
DROP SEQUENCE SEQ_TB_PESSOA;
DROP SEQUENCE SEQ_TB_FISICA;
DROP SEQUENCE SEQ_TB_JURIDICA;
DROP SEQUENCE SEQ_TB_CLIENTE;
DROP SEQUENCE SEQ_TB_ATENDIMENTO;
DROP SEQUENCE SEQ_TB_REGISTRO;
DROP SEQUENCE SEQ_TB_LOGATENDIMENTO;
DROP SEQUENCE SEQ_TB_LOGSERVICODOATENDIMENTO;
-- DROP PACKAGE
DROP PACKATE UTIL_PCK;
--------------------------------------------------
-- CREATE TYPE
--------------------------------------------------
CREATE OR REPLACE TYPE tp_livro AS OBJECT (
	cod INTEGER,
	descricao VARCHAR2(20)
);
CREATE OR REPLACE TYPE tp_desconto AS OBJECT(
	cod INTEGER,
	descricao VARCHAR2(20),
	valor NUMBER(8,2)
);
CREATE OR REPLACE TYPE tp_tipoServico AS OBJECT(
	cod INTEGER,
	descricao VARCHAR2(30)
);
CREATE OR REPLACE TYPE tp_servico AS OBJECT(
	cod INTEGER,
	descricao VARCHAR2(40),
	valor NUMBER(8,2),
	pertence REF tp_tipoServico
);
CREATE OR REPLACE TYPE tp_tipoFuncionario AS OBJECT(
	cod INTEGER,
	descricao VARCHAR2(20)
);
CREATE OR REPLACE TYPE tp_endereco AS OBJECT(
	descricao VARCHAR2(30),
	cep VARCHAR2(9),
	uf VARCHAR2(2),
	cidade VARCHAR2(45),
	bairro VARCHAR2(50),
	logradouro VARCHAR2(45),
	numero VARCHAR2(50)
);
CREATE OR REPLACE TYPE tp_fone AS OBJECT(
	ddd VARCHAR2(2),
	numero VARCHAR2(9)
);
CREATE OR REPLACE TYPE tp_fones AS VARRAY(3) OF tp_fone;
CREATE OR REPLACE TYPE tp_pessoa AS OBJECT(
	cod INTEGER,
	endereco tp_endereco,
	fones tp_fones,
	MEMBER PROCEDURE exibir_detalhes(SELF tp_pessoa),
	MAP MEMBER FUNCTION pessoaTOStr RETURN VARCHAR2
) NOT INSTANTIABLE NOT FINAL;
CREATE TYPE tp_fisica UNDER tp_pessoa (
	foto BLOB,
	cpf CHAR(11),
	nome VARCHAR2(45)
) FINAL;
CREATE TYPE tp_juridica UNDER tp_pessoa (
	cnpj CHAR(14),
	razaoSocial VARCHAR2(45)
) FINAL;
CREATE OR REPLACE TYPE tp_gratificacao AS OBJECT (
	periodo DATE,
	valor NUMBER(8,2)
) FINAL;
CREATE OR REPLACE TYPE tp_podeReceber  AS TABLE OF tp_gratificacao;
CREATE OR REPLACE TYPE tp_funcionario AS OBJECT(
	matricula VARCHAR2(10),
	dtAdmissao DATE,
	status CHAR(1),
	salario NUMBER(8,2),
	eh_uma REF tp_pessoa,
	supervisor REF tp_funcionario,
	tipoFuncionario REF tp_tipoFuncionario, 
	podeReceber_Gratificacoes tp_podeReceber
) FINAL;
CREATE OR REPLACE TYPE tp_cliente AS OBJECT (
	Cod VARCHAR2(10),
	dataRegistro DATE,
	pessoa REF tp_pessoa
) FINAL;
CREATE OR REPLACE TYPE tp_atendimento AS OBJECT(
	cod VARCHAR2(10),
	dataAtendimento DATE,
	valorTotal NUMBER(8,2),
	cliente REF tp_cliente,
	atendente REF tp_funcionario
) FINAL;
CREATE OR REPLACE TYPE tp_servicoDoAtendimento AS OBJECT (
	dataHoraRealizacao DATE,
	quantidade INTEGER,
	observacao VARCHAR2(150),
	valorDoServicoRealizado NUMBER(8,2),
	servico REF tp_servico,
	responsavel REF tp_funcionario,
	atendimento REF tp_atendimento,
	desconto REF tp_desconto
) FINAL;
CREATE OR REPLACE TYPE tp_registro AS OBJECT (
	numRegistro INTEGER,
	folha VARCHAR2(20),
	envolve REF tp_livro,
	servicoDoAtendimento REF tp_servicoDoAtendimento
);
CREATE OR REPLACE TYPE tp_LogAtendimento AS OBJECT (
	codLog INTEGER,
	dataOperacao DATE,
	usuario_sistema_id NUMBER,
	usuario_bd VARCHAR2(20),
	tipoOperacao CHAR(1),
	tupla tp_atendimento
) FINAL;
CREATE OR REPLACE TYPE tp_tuplaServicoDoAtendimento AS OBJECT (
	codAtendimento INTEGER,
	codDesconto INTEGER,
	codRegistro INTEGER,
	codResponsavel VARCHAR(10),
	dataHoraRealizacao DATE,
	codServico INTEGER,
	observacao VARCHAR2(150),
	valorDoServicoRealizado NUMBER(8,2), 
	quantidade INTEGER
) FINAL;
--------------------------------------------------
-- CREATE TABLE
--------------------------------------------------
CREATE TABLE tb_livro OF tp_livro (
	descricao NOT NULL,
	CONSTRAINT tb_livro_cod_pk PRIMARY KEY(cod),
	CONSTRAINT tb_livro_descricao_unico UNIQUE(descricao));
CREATE TABLE tb_desconto OF tp_desconto (
	descricao NOT NULL,
	valor NOT NULL,
	CONSTRAINT tb_desconto_cod_pk PRIMARY KEY(cod),
	CONSTRAINT tb_desconto_descricao_unico UNIQUE(descricao),
	CONSTRAINT tb_desconto_valor_check CHECK (valor > 0 AND valor <= 50)
);
CREATE TABLE tb_tipoServico OF tp_tipoServico (
	descricao NOT NULL,
	CONSTRAINT tb_tipoServico_cod_pk PRIMARY KEY(cod),
	CONSTRAINT tb_tipoServico_descricao_unico UNIQUE(descricao)
);
CREATE TABLE tb_servico OF tp_servico (
	descricao NOT NULL,
	valor NULL,
	CONSTRAINT tb_servico_cod_pk PRIMARY KEY(cod),
	CONSTRAINT tb_servico_descricao_unico UNIQUE(descricao),
	CONSTRAINT tb_servico_valor_check CHECK (valor IS NULL OR (valor IS NOT NULL AND valor > 0)),
	pertence WITH ROWID REFERENCES tb_tipoServico
);
CREATE TABLE tb_tipoFuncionario OF tp_tipoFuncionario (
	descricao NOT NULL,
	CONSTRAINT tb_tipoFuncionario_cod_pk PRIMARY KEY(cod),
	CONSTRAINT tb_tipoFuncionario_desc_unico UNIQUE(descricao)
);
CREATE TABLE tb_fisica OF tp_fisica (
	cpf NOT NULL,
	nome NOT NULL,
	foto NULL,
	CONSTRAINT tb_fisica_cod_pk PRIMARY KEY(cod),
	CONSTRAINT tb_fisica_cpf_unico UNIQUE(cpf)
);
CREATE TABLE tb_juridica of tp_juridica (
	cnpj NOT NULL,
	razaoSocial NOT NULL,
	endereco NOT NULL,
	CONSTRAINT tb_juridica_cod_pk PRIMARY KEY(cod),
	CONSTRAINT tb_juridica_cnpj_unico UNIQUE(cnpj)
);
CREATE TABLE tb_funcionario OF tp_funcionario ( 
	dtAdmissao NOT NULL,
	status NOT NULL,
	salario NOT NULL,
	CONSTRAINT tb_funcionario_matricula_pk PRIMARY KEY (matricula),
	CONSTRAINT tb_funcionario_status_check CHECK (STATUS = 'A' OR STATUS = 'I'),
	CONSTRAINT tb_funcionario_salario_check CHECK (salario >= 788.00),  
	eh_uma NOT NULL WITH ROWID REFERENCES tb_fisica, 
	supervisor NULL WITH ROWID REFERENCES tb_funcionario,
	tipoFuncionario NOT NULL WITH ROWID REFERENCES tb_tipoFuncionario,
	podeReceber_Gratificacoes NULL
) NESTED TABLE podeReceber_Gratificacoes STORE AS tb_nt_gratificacoesrecibidas; 
CREATE TABLE tb_cliente OF tp_cliente (
	dataRegistro NOT NULL,
	pessoa NOT NULL,
	CONSTRAINT tb_cliente_cod_pk PRIMARY KEY(cod)
);
CREATE TABLE tb_atendimento OF tp_atendimento (
	dataAtendimento NOT NULL,
	valorTotal NOT NULL,
	CONSTRAINT tb_atendimento_cod_pk PRIMARY KEY(cod),
	CONSTRAINT tb_atendimento_valTot_check CHECK (valorTotal >= 0.0),
	cliente NOT NULL WITH ROWID REFERENCES tb_cliente,
	atendente NOT NULL WITH ROWID REFERENCES tb_funcionario
);
CREATE TABLE tb_servicoDoAtendimento OF tp_servicoDoAtendimento (
	dataHoraRealizacao NOT NULL, 
	quantidade NOT NULL,
	observacao NULL,
	valorDoServicoRealizado NOT NULL,
	servico NOT NULL WITH ROWID REFERENCES tb_servico,
	responsavel NOT NULL WITH ROWID REFERENCES tb_funcionario,
	atendimento NOT NULL WITH ROWID REFERENCES tb_atendimento,
	desconto NULL WITH ROWID REFERENCES tb_desconto,
	CONSTRAINT tb_servDoAtend_valServ_chk CHECK (valorDoServicoRealizado>=0.0),
	CONSTRAINT tb_servDoAtend_pk PRIMARY KEY (dataHoraRealizacao)
);
CREATE TABLE tb_registro of tp_registro (
	folha NOT NULL, 
	CONSTRAINT tb_registro_cod_pk PRIMARY KEY (numRegistro),
	envolve WITH ROWID REFERENCES tb_livro,
	servicoDoAtendimento NOT NULL WITH ROWID REFERENCES tb_servicoDoAtendimento
CREATE TABLE tb_LogAtendimento of tp_LogAtendimento (
	codLog NOT NULL,
	dataOperacao NOT NULL,
	usuario_bd NOT NULL,
	tipoOperacao NOT NULL,
	tupla NOT NULL, 
	CONSTRAINT tb_log_LogAtend_tipoOpe_chk CHECK (tipoOperacao IN ('I','R','A')),
	CONSTRAINT tb_log_LogAtend_pk PRIMARY KEY (codLog)
);
CREATE TABLE tb_LogServicoDoAtendimento (
	codLog INTEGER NOT NULL,
	dataOperacao DATE NOT NULL,
	usuario_sistema_id NUMBER,
	usuario_bd VARCHAR2(20) NOT NULL,
	tipoOperacao CHAR(1) NOT NULL,
	tupla tp_tuplaServicoDoAtendimento NOT NULL, 
	CONSTRAINT tb_log_LogServAtend_tpOp_chk CHECK (tipoOperacao IN ('I','R','A')),
	CONSTRAINT tb_log_LogServAtend_pk PRIMARY KEY(codLog)
);
--------------------------------------------------
-- CREATE BODY
--------------------------------------------------
CREATE OR REPLACE TYPE BODY tp_pessoa AS
	MEMBER PROCEDURE exibir_detalhes (SELF tp_pessoa) IS 
	BEGIN
		DBMS_OUTPUT.ENABLE(1000000);
		DBMS_OUTPUT.PUT_LINE('Detalhes de uma Pessoa');
		DBMS_OUTPUT.PUT_LINE('CODIGO: ' || TO_CHAR(SELF.cod));
		DBMS_OUTPUT.PUT_LINE('ENDERECO: ' || SELF.endereco.descricao || ' - ' || SELF.endereco.cep);
	END;
	MAP MEMBER FUNCTION pessoaTOStr RETURN VARCHAR2 IS
		p VARCHAR2(15) := SELF.cod; 
		BEGIN       
			RETURN p;     
		END;
END;
--------------------------------------------------
-- CREATE SEQUENCE / TRIGGERS
--------------------------------------------------
CREATE SEQUENCE SEQ_TB_LIVRO
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_DESCONTO
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_TIPOSERVICO
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_SERVICO
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_TIPOFUNCIONARIO
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_FUNCIONARIO
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_PESSOA
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_FISICA
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_JURIDICA
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_CLIENTE
	INCREMENT BY 1
	START WITH 1;
CREATE SEUENCE SEQ_TB_ATENDIMENTO
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_REGISTRO
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_LOGATENDIMENTO
	INCREMENT BY 1
	START WITH 1;
CREATE SEQUENCE SEQ_TB_LOGSERVICODOATENDIMENTO
	INCREMENT BY 1
	START WITH 1;
--------------------------------------------------
-- CREATE PACKAGE
--------------------------------------------------
CREATE OR REPLACE PACKAGE util_pck IS
	usuario_sistema_id NUMBER;
END util_pck;
--------------------------------------------------
-- CREATE TRIGGER
--------------------------------------------------
CREATE OR REPLACE TRIGGER trg_logatendimento
AFTER INSERT OR UPDATE OR DELETE ON tb_atendimento  
FOR EACH ROW
DECLARE
BEGIN
	IF INSERTING THEN
		INSERT INTO tb_logatendimento VALUES (tp_atendimento(
			seq_tb_logatendimento.NEXTVAL, SYSDATE, util_pck.usuario_sistema_id, USER, 'I',
			tp_atendimento(:NEW.cod, :NEW.cliente, :NEW.atendente, :NEW.valorTotal, :NEW.dataAtendimento))
		);
	ELSIF UPDATING THEN
		INSERT INTO tb_logatendimento VALUES (tp_atendimento(
			seq_tb_logatendimento.NEXTVAL, SYSDATE, util_pck.usuario_sistema_id, USER, 'A',
			tp_atendimento(:NEW.cod, :NEW.cliente, :NEW.atendente, :NEW.valorTotal, :NEW.dataAtendimento))
		);
	ELSIF DELETING THEN
		INSERT INTO tb_logatendimento VALUES (tp_atendimento(
			seq_tb_logatendimento.NEXTVAL, SYSDATE, util_pck.usuario_sistema_id, USER, 'R',
			tp_atendimento(:OLD.cod, :OLD.cliente, :OLD.atendente, :OLD.valorTotal, :OLD.dataAtendimento))
		);
	END IF;
END trg_logatendimento;
--------------------------------------------------
-- CREATE INDEX
--------------------------------------------------
CREATE INDEX idx_tb_atendimento_data ON tb_atendimento (dataatendimento);
CREATE INDEX idx_tb_cliente_data ON tb_cliente (dataregistro);
CREATE INDEX idx_tb_fisica_nome ON tb_fisica (nome);
CREATE INDEX idx_tb_fisica_cpf_nome ON tb_fisica (cpf,nome);
CREATE INDEX idx_tb_funcionario_status ON tb_funcionario (status);
CREATE INDEX idx_tb_funcionario_salario ON tb_funcionario (salario);
CREATE INDEX idx_tb_funcionario_dtadmissao ON tb_funcionario (dtadmissao);
CREATE INDEX idx_tb_juridica_cnpj_rzsoc ON tb_juridica (cnpj,razaosocial);
CREATE INDEX idx_tb_registro_folha ON tb_registro (folha);
CREATE INDEX idx_tb_servico_valor ON tb_servico (valor);
CREATE INDEX idx_tb_servico_descval ON tb_servico (descricao,valor);
CREATE INDEX idx_tb_log_atendimento_dataop ON tb_logatendimento (dataoperacao);
CREATE INDEX idx_tb_log_atendimento_tipoop ON tb_logatendimento (tipooperacao);
CREATE INDEX idx_tb_log_atendimento_dtop ON tb_logatendimento (dataoperacao,tipooperacao);
CREATE INDEX idx_tb_log_servdoatend_dataop ON tb_logservicodoatendimento (dataoperacao);
CREATE INDEX idx_tb_log_servdoatend_tipoop ON tb_logservicodoatendimento (tipooperacao);
CREATE INDEX idx_tb_log_servdoatend_dtop ON tb_logservicodoatendimento (dataoperacao,tipooperacao);
--------------------------------------------------
-- CARGA DE DADOS
--------------------------------------------------
-- >>>>> TB_TIPOSERVICO
INSERT INTO TB_TIPOSERVICO VALUES (TP_TIPOSERVICO(SEQ_TB_TIPOSERVICO.NEXTVAL,'AUTENTICACAO DE DOCUMENTOS'));
INSERT INTO TB_TIPOSERVICO VALUES (TP_TIPOSERVICO(SEQ_TB_TIPOSERVICO.NEXTVAL,'REGISTRAR FIRMA'));
INSERT INTO TB_TIPOSERVICO VALUES (TP_TIPOSERVICO(SEQ_TB_TIPOSERVICO.NEXTVAL,'REGISTRAR CLIENTE'));
-- >>>>> TB_SERVICO
INSERT INTO TB_SERVICO VALUES (TP_SERVICO(SEQ_TB_SERVICO.NEXTVAL,'SERVIÇO DE REGISTRO DE CLIENTE', 5.00, 
        (SELECT REF(T) FROM TB_TIPOSERVICO T WHERE T.DESCRICAO='REGISTRAR CLIENTE')));
INSERT INTO TB_SERVICO VALUES (TP_SERVICO(SEQ_TB_SERVICO.NEXTVAL,'SERVIÇO DE REGISTRO DE FIRMA', 15.00, 
        (SELECT REF(T) FROM TB_TIPOSERVICO T WHERE T.DESCRICAO='REGISTRAR FIRMA')));        
INSERT INTO TB_SERVICO VALUES (TP_SERVICO(SEQ_TB_SERVICO.NEXTVAL,'SERVIÇO DE AUTENTICACAO DE DOCUMENTOS', 2.00, 
        (SELECT REF(T) FROM TB_TIPOSERVICO T WHERE T.DESCRICAO='AUTENTICACAO DE DOCUMENTOS')));                
-- >>>>> TB_LIVRO
INSERT INTO TB_LIVRO VALUES (TP_LIVRO(SEQ_TB_LIVRO.NEXTVAL,'LIVRO 1'));
INSERT INTO TB_LIVRO VALUES (TP_LIVRO(SEQ_TB_LIVRO.NEXTVAL,'LIVRO 2'));
INSERT INTO TB_LIVRO VALUES (TP_LIVRO(SEQ_TB_LIVRO.NEXTVAL,'LIVRO 3'));
-- >>>>> TB_DESCONTO
INSERT INTO TB_DESCONTO VALUES (TP_DESCONTO(SEQ_TB_DESCONTO.NEXTVAL,'DESCONTO DE 10%',10));
INSERT INTO TB_DESCONTO VALUES (TP_DESCONTO(SEQ_TB_DESCONTO.NEXTVAL,'DESCONTO DE 20%',20));
INSERT INTO TB_DESCONTO VALUES (TP_DESCONTO(SEQ_TB_DESCONTO.NEXTVAL,'DESCONTO DE 30%',30));
-- >>>>> TB_TIPOFUNCIONARIO
INSERT INTO TB_TIPOFUNCIONARIO VALUES (TP_TIPOFUNCIONARIO(SEQ_TB_TIPOFUNCIONARIO.NEXTVAL,'ATENDENTE'));
INSERT INTO TB_TIPOFUNCIONARIO VALUES (TP_TIPOFUNCIONARIO(SEQ_TB_TIPOFUNCIONARIO.NEXTVAL,'TABELIÃO'));
INSERT INTO TB_TIPOFUNCIONARIO VALUES (TP_TIPOFUNCIONARIO(SEQ_TB_TIPOFUNCIONARIO.NEXTVAL,'ESCREVENTE'));
-- >>>>> TB_FISICA
INSERT INTO TB_FISICA VALUES (
	TP_FISICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('CONJUNTO','64023224','PI','TERESINA','LOURIVAL PARENTE','QUADRA 22 BLOCO 03','204'),
		TP_FONES(TP_FONE('89','99762610'),TP_FONE('86','32275682'),TP_FONE('89','35222827')), 
		NULL, --FOTO DA PESSOA FISICA
		'01210449390', 
		'WILTON MOREIRA DE SANTANA JUNIOR'
	)
);
INSERT INTO TB_FISICA VALUES (
	TP_FISICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('CASA','64800000','PI','FLORIANO','ALTO DA GUIA','RUA JOSÉ OLEGÁRIO','33'),
		TP_FONES(TP_FONE('89','99723512'),TP_FONE('89','35156428')), 
		NULL, --FOTO DA PESSOA FISICA
		'66363144353', 
		'VERONICA SANTOS GUIMARAES DE SANTANA'
	)
);
INSERT INTO TB_FISICA VALUES (
	TP_FISICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('VILA','64850000','PE','RECIFE','CANDEIAS','RUA MARQUES DE MAUÁ','421'),
		TP_FONES(TP_FONE('85','88563512')), 
		NULL, --FOTO DA PESSOA FISICA
		'99999999999', 
		'CLARISSA MOREIRA DE SANTANA'
	)
);
INSERT INTO TB_FISICA VALUES (
	TP_FISICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('CENTRO','64800000','PI','FLORIANO','CENTRO','RUA FERNANDO MARQUES','1421'),
		TP_FONES(TP_FONE('89','45362345')), 
		NULL, --FOTO DA PESSOA FISICA
		'91923799324', 
		'JOSUE BONAPARTE NAPOLEAO' -- TABELIAO
	)
);
INSERT INTO TB_FISICA VALUES (
	TP_FISICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('CONJUNTO','64800000','PI','FLORIANO','MELADAO','PEDRO SIMPLICIO','654'),
		TP_FONES(TP_FONE('89','99762634')), 
		NULL, --FOTO DA PESSOA FISICA
		'99998799265', 
		'MARIA SANTANA DO LIVRAMENTO SILVA' -- ESCREVENTE
	)
);
INSERT INTO TB_FISICA VALUES (
	TP_FISICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('CASA','64800000','PI','FLORIANO','AEROPORTO','RUA HERMINIO BRAGA','37'),
		TP_FONES(TP_FONE('89','88643467')), 
		NULL,--FOTO DA PESSOA FISICA
		'64538275932',
 		'JULY MARTINS TOLEDO' -- ATENDENTE
	)
);
-- >>>>> TB_JURIDICA
INSERT INTO TB_JURIDICA VALUES (
	TP_JURIDICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('AVENIDA','64023543','PI','TERESINA','CENTRO','JOAQUIM RIBEIRO','343'),
		TP_FONES(TP_FONE('89','32114512')),  
		'34542536475651',
		'RR CONTAS'
	)
);
INSERT INTO TB_JURIDICA VALUES (
	TP_JURIDICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('AVENIDA','64023543','PI','TERESINA','CENTRO','JOAQUIM RIBEIRO','343'),
		TP_FONES(TP_FONE('89','32114512')),  
		'56742536475222',
		'ENGERCOPI MATERIAL DE CONTRUÇÕES'
	)
);
INSERT INTO TB_JURIDICA VALUES (
	TP_JURIDICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('AVENIDA','64023543','PI','TERESINA','CENTRO','JOAQUIM RIBEIRO','343'),
		TP_FONES(TP_FONE('89','32114512')),  
		'25642536475789',
		'STESOM AUTO ELETRICA'
	)
);
INSERT INTO TB_JURIDICA VALUES (
	TP_JURIDICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('CONJUNTO','64345456','PI','TERESINA','JOCKEY','MARTINS DEL MAR','1343'),
		TP_FONES(TP_FONE('86','32364512')),  
		'18477329840583',
		'ELITE GIRLS MODAS'
	)
);
INSERT INTO TB_JURIDICA VALUES (
	TP_JURIDICA(
		SEQ_TB_PESSOA.NEXTVAL,
		TP_ENDERECO('AVENIDA','64800000','PI','FLORIANO','CENTRO','ELIAS OKA','23'),
		TP_FONES(TP_FONE('89','35222546')),  
		'45793225432237',
		'GRIFES MODAS FLORIANO'
	)
);
-- >>>>> TB_CLIENTE
INSERT INTO TB_CLIENTE VALUES (
	TP_CLIENTE(
		SEQ_TB_CLIENTE.NEXTVAL,
		TO_DATE('21/11/2013','dd/mm/yyyy'),
		(SELECT REF(P) FROM TB_FISICA P WHERE P.CPF='01210449390')
	)
);
INSERT INTO TB_CLIENTE VALUES (
	TP_CLIENTE(
		SEQ_TB_CLIENTE.NEXTVAL,
		TO_DATE('21/11/2013','dd/mm/yyyy'),
		(SELECT REF(P) FROM TB_FISICA P WHERE P.CPF='66363144353')
	)
);
INSERT INTO TB_CLIENTE VALUES (
	TP_CLIENTE(
		SEQ_TB_CLIENTE.NEXTVAL,
		TO_DATE('21/11/2013','dd/mm/yyyy'),
		(SELECT REF(P) FROM TB_FISICA P WHERE P.CPF='99999999999')
	)
);
INSERT INTO TB_CLIENTE VALUES (
	TP_CLIENTE(
		SEQ_TB_CLIENTE.NEXTVAL,
		TO_DATE('06/05/2012','dd/mm/yyyy'),
		(SELECT REF(P) FROM TB_JURIDICA P WHERE P.CNPJ='34542536475651')
	)
);
INSERT INTO TB_CLIENTE VALUES (
	TP_CLIENTE(
		SEQ_TB_CLIENTE.NEXTVAL,
		TO_DATE('12/04/2012','dd/mm/yyyy'),
		(SELECT REF(P) FROM TB_JURIDICA P WHERE P.CNPJ='56742536475222')
	)
);
INSERT INTO TB_CLIENTE VALUES (
	TP_CLIENTE(
		SEQ_TB_CLIENTE.NEXTVAL,
		TO_DATE('20/01/2014','dd/mm/yyyy'),
		(SELECT REF(P) FROM TB_JURIDICA P WHERE P.CNPJ='25642536475789')
	)
);
INSERT INTO TB_CLIENTE VALUES (
	TP_CLIENTE(
		SEQ_TB_CLIENTE.NEXTVAL,
		TO_DATE('15/02/2015','dd/mm/yyyy'),
		(SELECT REF(P) FROM TB_JURIDICA P WHERE P.CNPJ='18477329840583')
	)
);
INSERT INTO TB_CLIENTE VALUES (
	TP_CLIENTE(
		SEQ_TB_CLIENTE.NEXTVAL,
		TO_DATE('20/10/2012','dd/mm/yyyy'),
		(SELECT REF(P) FROM TB_JURIDICA P WHERE P.CNPJ='45793225432237')
	)
);
INSERT INTO TB_FUNCIONARIO VALUES (
	TP_FUNCIONARIO(
		SEQ_TB_FUNCIONARIO.NEXTVAL,
		TO_DATE('21/03/2015','dd/mm/yyyy'),
 		'A',
 		890.00,
 		(SELECT REF(P) FROM TB_FISICA P WHERE P.CPF='99998799265'),
 		NULL,
 		(SELECT REF(TF) FROM TB_TIPOFUNCIONARIO TF WHERE TF.DESCRICAO='ATENDENTE'),
 		TP_PODERECEBER(tp_gratificacao(TO_DATE('04/2015','mm/yyyy'),100.00))                                                              
 	)
);
-- >>>>> TB_FUNCIONARIO
INSERT INTO TB_FUNCIONARIO VALUES (
	TP_FUNCIONARIO(
		SEQ_TB_FUNCIONARIO.NEXTVAL,
		TO_DATE('12/04/2015','dd/mm/yyyy'),
		'A',
		1600.00,
		(SELECT REF(P) FROM TB_FISICA P WHERE P.CPF='64538275932'),
 		NULL,
		(SELECT REF(TF) FROM TB_TIPOFUNCIONARIO TF WHERE TF.DESCRICAO='ESCREVENTE'),
		TP_PODERECEBER(
			tp_gratificacao(TO_DATE('05/2015','mm/yyyy'),200.00),
			tp_gratificacao(TO_DATE('06/2015','mm/yyyy'),250.00)
		)                                              
	)
);
INSERT INTO TB_FUNCIONARIO VALUES (
	TP_FUNCIONARIO(
		SEQ_TB_FUNCIONARIO.NEXTVAL,
		TO_DATE('05/06/2015','dd/mm/yyyy'),
		'A',
		5500.00,
		(SELECT REF(P) FROM TB_FISICA P WHERE P.CPF='91923799324'),
		NULL,
		(SELECT REF(TF) FROM TB_TIPOFUNCIONARIO TF WHERE TF.DESCRICAO='TABELIÃO'),
		NULL                                                              
	)
);
-- Definindo supervisores dos funcionarios
UPDATE TB_FUNCIONARIO TF
	SET TF.SUPERVISOR = (SELECT REF(TFSP) FROM TB_FUNCIONARIO TFSP WHERE DEREF(TFSP.EH_UMA).CPF='64538275932')
	WHERE DEREF(TF.EH_UMA).CPF='99998799265';
UPDATE TB_FUNCIONARIO TF 
	SET TF.SUPERVISOR=(SELECT REF(TFSP) FROM TB_FUNCIONARIO TFSP WHERE DEREF(TFSP.EH_UMA).CPF='91923799324')
	WHERE DEREF(TF.EH_UMA).CPF='64538275932';
-- >>>>> TB_ATENDIMENTO
DECLARE
	BEGIN
		util_pck.usuario_sistema_id := 3;
		INSERT INTO TB_ATENDIMENTO VALUES (
			TP_ATENDIMENTO(
				SEQ_TB_ATENDIMENTO.NEXTVAL,
				to_date('21/04/2015','dd/mm/yyyy'),
				0.00,
				(SELECT REF(T) FROM TB_CLIENTE T WHERE DEREF(T.PESSOA) IS OF (TP_FISICA) AND TREAT((DEREF(T.PESSOA)) AS TP_FISICA).CPF='01210449390'),   
				(SELECT REF(F) FROM TB_FUNCIONARIO F WHERE ((DEREF(F.EH_UMA))).CPF='99998799265' AND ((DEREF(F.TIPOFUNCIONARIO))).DESCRICAO='ATENDENTE')   
			)
		);
	END;
COMMIT;
DECLARE
	BEGIN
		util_pck.usuario_sistema_id := 3;
		INSERT INTO TB_ATENDIMENTO VALUES (
			TP_ATENDIMENTO(
				SEQ_TB_ATENDIMENTO.NEXTVAL,
				TO_DATE('18/02/2015','dd/mm/yyyy'),
				0.00,
				(SELECT REF(T) FROM TB_CLIENTE T WHERE DEREF(T.PESSOA) IS OF (TP_FISICA) AND TREAT((DEREF(T.PESSOA)) AS TP_FISICA).CPF='01210449390'),
				(SELECT REF(F) FROM TB_FUNCIONARIO F WHERE ((DEREF(F.EH_UMA))).CPF='99998799265' AND ((DEREF(F.TIPOFUNCIONARIO))).DESCRICAO='ATENDENTE')   
			)
		);
	END;
COMMIT;
DECLARE
	BEGIN
		util_pck.usuario_sistema_id := 3;
		INSERT INTO TB_ATENDIMENTO VALUES (
			TP_ATENDIMENTO(
				SEQ_TB_ATENDIMENTO.NEXTVAL,
				TO_DATE('17/03/2015','dd/mm/yyyy'),
				0.00,
				(SELECT REF(T) FROM TB_CLIENTE T WHERE DEREF(T.PESSOA) IS OF (TP_JURIDICA) AND TREAT((DEREF(T.PESSOA)) AS TP_JURIDICA).CNPJ='45793225432237'),   
				(SELECT REF(F) FROM TB_FUNCIONARIO F WHERE  ((DEREF(F.EH_UMA))).CPF='99998799265' AND ((DEREF(F.TIPOFUNCIONARIO))).DESCRICAO='ATENDENTE')   
			)
		);
	END;
COMMIT;
DECLARE
	BEGIN
		util_pck.usuario_sistema_id := 3;
		INSERT INTO TB_ATENDIMENTO VALUES (
			TP_ATENDIMENTO(
				SEQ_TB_ATENDIMENTO.NEXTVAL,
				TO_DATE('18/03/2015','dd/mm/yyyy'),
				0.00,
				(SELECT REF(T) FROM TB_CLIENTE T WHERE DEREF(T.PESSOA) IS OF (TP_JURIDICA) AND TREAT((DEREF(T.PESSOA)) AS TP_JURIDICA).CNPJ='34542536475651'),   
				(SELECT REF(F) FROM TB_FUNCIONARIO F WHERE  ((DEREF(F.EH_UMA))).CPF='99998799265' AND ((DEREF(F.TIPOFUNCIONARIO))).DESCRICAO='ATENDENTE')   
			)
		);
	END;
COMMIT;
-- >>>>> TB_SERVICODOATENDIMENTO
-- item de servico sem desconto no atendimento 1
INSERT INTO TB_SERVICODOATENDIMENTO VALUES (
	TP_SERVICODOATENDIMENTO(
		TO_DATE('21/04/2015 10:14:41','dd/mm/yyyy HH24:MI:SS'),
		2,
		'Autenticacao de um documentos de habilitação',
		(((SELECT S.VALOR FROM TB_SERVICO S WHERE S.DESCRICAO='SERVIÇO DE AUTENTICACAO DE DOCUMENTOS') * 2) * (1 - ((SELECT D.VALOR FROM TB_DESCONTO D WHERE D.COD = 1) / 100))),
		(SELECT REF(S) FROM TB_SERVICO S WHERE S.DESCRICAO='SERVIÇO DE AUTENTICACAO DE DOCUMENTOS'),   
		(SELECT REF(F) FROM TB_FUNCIONARIO F WHERE DEREF(F.TIPOFUNCIONARIO).DESCRICAO='ESCREVENTE' AND TREAT(DEREF(F.EH_UMA)AS TP_FISICA).CPF='64538275932'),         
		(SELECT REF(ATEND) FROM TB_ATENDIMENTO ATEND WHERE ATEND.COD = 1),
		(SELECT REF(D) FROM TB_DESCONTO D WHERE D.COD = 1)
	)
);
-- item de servico do atendimento com desconto no atendimento 1
INSERT INTO TB_SERVICODOATENDIMENTO VALUES (
	TP_SERVICODOATENDIMENTO(
		TO_DATE('21/04/2015 10:16:26','dd/mm/yyyy HH24:MI:SS'),
		4,
		'Registrar firma para comprar imovel novo na rua jose olegario correia',
		(((SELECT S.VALOR FROM TB_SERVICO S WHERE S.DESCRICAO='SERVIÇO DE REGISTRO DE FIRMA') * 4) * (1 - ((SELECT D.VALOR FROM TB_DESCONTO D WHERE D.COD = 1) / 100))),
		(SELECT REF(S) FROM TB_SERVICO S WHERE S.DESCRICAO='SERVIÇO DE REGISTRO DE FIRMA'),   
		(SELECT REF(F) FROM TB_FUNCIONARIO F WHERE DEREF(F.TIPOFUNCIONARIO).DESCRICAO='TABELIÃO' AND TREAT(DEREF(F.EH_UMA)AS TP_FISICA).CPF='91923799324'),         
		(SELECT REF(ATEND) FROM TB_ATENDIMENTO ATEND WHERE ATEND.COD = 1),
		(SELECT REF(D) FROM TB_DESCONTO D WHERE D.COD = 1)
	)
);
-- item de servico do atendimento sem desconto no atendimento 1 e registrar no arquivo do cartorio
INSERT INTO TB_SERVICODOATENDIMENTO VALUES (
	TP_SERVICODOATENDIMENTO(
		TO_DATE('21/04/2015 10:18:26','dd/mm/yyyy HH24:MI:SS'),
		1,
		'Registrar firma para comprar apartamento no centro de floriano',   
		(((SELECT S.VALOR FROM TB_SERVICO S WHERE S.DESCRICAO='SERVIÇO DE REGISTRO DE FIRMA') * 1) * (1 - ((SELECT D.VALOR FROM TB_DESCONTO D WHERE D.COD = 1) / 100))),
		(SELECT REF(S) FROM TB_SERVICO S WHERE S.DESCRICAO='SERVIÇO DE REGISTRO DE FIRMA'),   
		(SELECT REF(F) FROM TB_FUNCIONARIO F WHERE DEREF(F.TIPOFUNCIONARIO).DESCRICAO='TABELIÃO' AND TREAT(DEREF(F.EH_UMA)AS TP_FISICA).CPF='91923799324'),         
		(SELECT REF(ATEND) FROM TB_ATENDIMENTO ATEND WHERE ATEND.COD = 1),
		(SELECT REF(D) FROM TB_DESCONTO D WHERE D.COD = 1)
	)
);
--registro do item de servico no arquivo do cartorio no livro 1 na folha 1 registro 1
INSERT INTO TB_REGISTRO VALUES (
	TP_REGISTRO(
		SEQ_TB_REGISTRO.NEXTVAL,
		1,
		(SELECT REF(L) 
			FROM TB_LIVRO L 
			WHERE L.COD=1 AND 
				L.DESCRICAO='LIVRO 1'),  
		(SELECT REF(S) 
			FROM TB_SERVICODOATENDIMENTO S 
				WHERE S.OBSERVACAO = 'Registrar firma para comprar apartamento no centro de floriano' AND 
					S.DATAHORAREALIZACAO = TO_DATE('21/04/2015 10:18:26','dd/mm/yyyy HH24:MI:SS') AND 
					DEREF(S.ATENDIMENTO).COD=1)
	)
);
-- Atualiza o total de cada servico atendido
UPDATE
	TB_SERVICODOATENDIMENTO SA
SET 
	SA.VALORDOSERVICOREALIZADO = SA.QUANTIDADE * DEREF(SA.SERVICO).VALOR * 
	(CASE WHEN (DEREF(SA.DESCONTO).VALOR IS NOT NULL) THEN ((100 - DEREF(SA.DESCONTO).VALOR)/100) ELSE 1 END)
WHERE
	DEREF(SA.ATENDIMENTO).COD=1;
--Atualiza o total do Atendimento
UPDATE TB_ATENDIMENTO TA
	SET TA.VALORTOTAL = (SELECT SUM(ISA.VALORDOSERVICOREALIZADO) 
							FROM TB_SERVICODOATENDIMENTO ISA 
							WHERE DEREF(ISA.ATENDIMENTO).COD=TA.COD)
WHERE TA.COD=1;
--------------------------------------------------
-- CONSULTAS
--------------------------------------------------
-- >>>>> RETORNA TODOS OS CLIENTES PESSOA FISICA DO CARTORIO
SELECT 
	T.COD AS CODCLIENTE, T.DATAREGISTRO AS DATAREGISTROCLIENTE, T.pessoa.COD AS CODPESSOAFISICA, 
	deref(t.pessoa), (TREAT((DEREF(T.PESSOA)) AS TP_FISICA).CPF) AS CPF, 
	(TREAT((DEREF(T.PESSOA)) AS TP_FISICA).NOME) AS NOME
FROM 
	TB_CLIENTE T
WHERE
	DEREF(T.PESSOA) IS OF (TP_FISICA)
ORDER BY
	NOME, CPF;
-- >>>>> RETORNA TODOS OS CLIENTES PESSOA JURIDICA DO CARTORIO
SELECT 
	T.COD AS CODCLIENTE, T.DATAREGISTRO AS DATAREGISTROCLIENTE, T.pessoa.COD AS CODPESSOAJURIDICA,
	DEREF(t.pessoa), (TREAT((DEREF(T.PESSOA)) AS TP_JURIDICA).CNPJ) AS CNPJ,
	(TREAT((DEREF(T.PESSOA)) AS TP_JURIDICA).RAZAOSOCIAL) AS RAZAOSOCIAL
FROM
	TB_CLIENTE T
WHERE
	DEREF(T.PESSOA) IS OF (TP_JURIDICA)
ORDER BY 
	RAZAOSOCIAL, CNPJ;
-- >>>>> RETORNA TODOS OS CLIENTES DO CARTORIO
SELECT
	*
FROM 
	(
		(SELECT
			T.COD AS CODCLIENTE, T.DATAREGISTRO AS DATAREGISTROCLIENTE, 
			(TREAT((DEREF(T.PESSOA)) AS TP_FISICA).CPF) AS CPF_CNPJ, 'PESSOA_FISICA' AS TIPO, 
			(TREAT((DEREF(T.PESSOA)) AS TP_FISICA).NOME) AS NOME
		FROM
			TB_CLIENTE T
		WHERE
			DEREF(T.PESSOA) IS OF (TP_FISICA))
		UNION
		(SELECT 
			T.COD AS CODCLIENTE, T.DATAREGISTRO AS DATAREGISTROCLIENTE,
			(TREAT((DEREF(T.PESSOA)) AS TP_JURIDICA).CNPJ) AS CPF_CNPJ,
			'PESSOA_JURIDICA' AS TIPO, (TREAT((DEREF(T.PESSOA)) AS TP_JURIDICA).RAZAOSOCIAL) AS RAZAOSOCIAL
FROM
	TB_CLIENTE T
WHERE
	DEREF(T.PESSOA) IS OF (TP_JURIDICA))) CLIENTES
ORDER BY 
	CLIENTES.TIPO, CLIENTES.NOME ASC, CLIENTES.CPF_CNPJ;
-- >>>>> LISTA TODOS OS FUNCIONARIOS DO CARTORIO
SELECT F.* FROM TB_FUNCIONARIO F;
-- >>>>> LISTA FUNCIONARIOS COM SEUS SUPERVISORES 
SELECT
	DEREF(TF.TIPOFUNCIONARIO).DESCRICAO AS TIPO_FUNCIONARIO, TF.MATRICULA, TF.DTADMISSAO, 
	TF.STATUS, TF.SALARIO, DEREF(TF.EH_UMA).CPF AS CPF, DEREF(TF.EH_UMA).NOME AS NOME, 
	DEREF(TF.SUPERVISOR.EH_UMA).NOME AS SUPERVISOR
--,TF.PODERECEBER_GRATIFICACOES AS GRATIFICACOES_RECEBIDAS,
--,DEREF(TF.PODERECEBER_GRATIFICACOES)
--,TF.*
--g.*
FROM
	tb_funcionario tf;
--where tf.supervisor is not null and tf.supervisor is not dangling;
--, table(tf.podereceber_gratificacoes) g;
-- >>>>> GRATIFICACOES RECEBIDAS POR UM DETERMINADO FUNCIONARIO DE MATRICULA X
SELECT
	DEREF(TF.TIPOFUNCIONARIO).DESCRICAO AS TIPO_FUNCIONARIO, TF.MATRICULA, TF.DTADMISSAO, 
	TF.STATUS, TF.SALARIO AS SALARIO_BASE, DEREF(TF.EH_UMA).CPF AS CPF, 
	DEREF(TF.EH_UMA).NOME AS NOME,
--DEREF(TF.SUPERVISOR.HE_UMA).NOME AS SUPERVISOR
--,TF.PODERECEBER_GRATIFICACOES AS GRATIFICACOES_RECEBIDAS,
--,DEREF(TF.PODERECEBER_GRATIFICACOES)
--,TF.*
--,g.*
	g.periodo AS periodo_GRATIFICACAO, g.valor AS GRATIFICACAO, (G.VALOR + SALARIO) AS SALARIO_NO_PERIODO
FROM
	tb_funcionario tf
	INNER JOIN table(tf.podereceber_gratificacoes) g ON (tf.matricula = 1)
ORDER BY 
	PERIODO ASC;
-- >>>>> LISTA TODOS OS ATENDIMENTOS REALIZADOS A TODOS OS CLIENTES PESSOAS FISICAS ORDENADOS POR DATA
SELECT 
	TA.DATAATENDIMENTO,
	DEREF(TA.ATENDENTE).MATRICULA AS MATRICULAATENDENTE,  
	TREAT(DEREF(DEREF(TA.ATENDENTE).EH_UMA)AS TP_FISICA).CPF AS CPFATENDENTE,
	TREAT(DEREF(DEREF(TA.ATENDENTE).EH_UMA)AS TP_FISICA).NOME AS NOMEATENDENTE,  
	DEREF(TA.CLIENTE).COD   AS CODCLIENTE,  
	TREAT(DEREF(DEREF(TA.CLIENTE).PESSOA) AS TP_FISICA).CPF   AS CPFCLIENTE,
	TREAT(DEREF(DEREF(TA.CLIENTE).PESSOA) AS TP_FISICA).NOME   AS NOMECLIENTE,
	TA.VALORTOTAL
FROM
	TB_ATENDIMENTO TA 
WHERE   
	DEREF(DEREF(TA.CLIENTE).PESSOA) IS OF (TP_FISICA)  
ORDER BY
	DATAATENDIMENTO;
-- >>>>> LISTA TODOS OS ATENDIMENTOS REALIZADOS A TODOS OS CLIENTES PESSOAS JURIDICAS ORDENADOS POR DATA
SELECT 
	TA.DATAATENDIMENTO,
	DEREF(TA.ATENDENTE).MATRICULA AS MATRICULAATENDENTE,  
	TREAT(DEREF(DEREF(TA.ATENDENTE).EH_UMA)AS TP_FISICA).CPF AS CPFATENDENTE,
	TREAT(DEREF(DEREF(TA.ATENDENTE).EH_UMA)AS TP_FISICA).NOME AS NOMEATENDENTE,  
	DEREF(TA.CLIENTE).COD   AS CODCLIENTE,  
	TREAT(DEREF(DEREF(TA.CLIENTE).PESSOA) AS TP_JURIDICA).CNPJ   AS CNPJCLIENTE,
	TREAT(DEREF(DEREF(TA.CLIENTE).PESSOA) AS TP_JURIDICA).RAZAOSOCIAL   AS NOMECLIENTE,
	TA.VALORTOTAL AS VALORTOTAL
FROM
	TB_ATENDIMENTO TA 
WHERE
	DEREF(DEREF(TA.CLIENTE).PESSOA) IS OF (TP_JURIDICA)  
ORDER BY
	DATAATENDIMENTO;
-- >>>>> LISTA TODOS OS ATENDIMENTOS REALIZADOS A TODOS OS TIPOS DE CLIENTES ORDENADOS POR DATA E ATENDIMENTO E TIPO DE CLIENTE(FISICA OU JURIDICA)
SELECT
	*
FROM
	(
		(SELECT 
			TA.COD AS CODATENDIMENTO,
			TA.DATAATENDIMENTO,
			DEREF(TA.ATENDENTE).MATRICULA AS MATRICULAATENDENTE,  
			TREAT(DEREF(DEREF(TA.ATENDENTE).EH_UMA)AS TP_FISICA).CPF AS CPFATENDENTE,
			TREAT(DEREF(DEREF(TA.ATENDENTE).EH_UMA)AS TP_FISICA).NOME AS NOMEATENDENTE,  
			DEREF(TA.CLIENTE).COD AS CODCLIENTE,  
			TREAT(DEREF(DEREF(TA.CLIENTE).PESSOA) AS TP_FISICA).CPF AS CPFCNPJCLIENTE,
			TREAT(DEREF(DEREF(TA.CLIENTE).PESSOA) AS TP_FISICA).NOME AS NOMECLIENTE,
			TA.VALORTOTAL AS VALORTOTAL,
			'CLIENTE PESSOA FISICA' AS TIPO_CLIENTE
		FROM
			TB_ATENDIMENTO TA 
		WHERE
			DEREF(DEREF(TA.CLIENTE).PESSOA) IS OF (TP_FISICA)  )
		UNION
		(SELECT 
			TA.COD AS CODATENDIMENTO,
			TA.DATAATENDIMENTO,
			DEREF(TA.ATENDENTE).MATRICULA AS MATRICULAATENDENTE,  
			TREAT(DEREF(DEREF(TA.ATENDENTE).EH_UMA)AS TP_FISICA).CPF AS CPFATENDENTE,
			TREAT(DEREF(DEREF(TA.ATENDENTE).EH_UMA)AS TP_FISICA).NOME AS NOMEATENDENTE,  
			DEREF(TA.CLIENTE).COD AS CODCLIENTE,  
			TREAT(DEREF(DEREF(TA.CLIENTE).PESSOA) AS TP_JURIDICA).CNPJ AS CPFCNPJCLIENTE,
			TREAT(DEREF(DEREF(TA.CLIENTE).PESSOA) AS TP_JURIDICA).RAZAOSOCIAL AS NOMECLIENTE,
			TA.VALORTOTAL AS VALORTOTAL,
			'CLIENTE PESSOA JURIDICA' AS TIPO_CLIENTE
		FROM
			TB_ATENDIMENTO TA
		WHERE
			DEREF(DEREF(TA.CLIENTE).PESSOA) IS OF (TP_JURIDICA))
	) CLI
ORDER BY
	CLI.TIPO_CLIENTE, CLI.DATAATENDIMENTO;
-- >>>>> BUSCAR TODOS OS ITENS DO ATENDIMENTO DE COD 1 
SELECT
	DEREF(isa.atendimento).cod AS codAtendimento,
	CASE WHEN ((TREAT(DEREF(DEREF(DEREF(isa.atendimento).cliente).pessoa) AS TP_JURIDICA).cod) IS NOT NULL) 
		THEN 'PESSOA JURIDICA' 
		ELSE 'PESSOA FÍSICA' 
	END AS TIPOCLIENTE,
	CASE WHEN ((TREAT(DEREF(DEREF(DEREF(isa.atendimento).cliente).pessoa) AS TP_JURIDICA).cod) IS NOT NULL) 
		THEN (TREAT(DEREF(DEREF(DEREF(isa.atendimento).cliente).pessoa) AS TP_JURIDICA).cnpj) 
		ELSE (TREAT(deref(deref(deref(isa.atendimento).cliente).pessoa) AS TP_FISICA).cpf)
	END AS CLIENTE,
	isa.dataHoraRealizacao, isa.observacao, DEREF(isa.servico).descricao AS servico, 
	DEREF(isa.servico).valor AS valorUnitario, isa.quantidade AS quantidade, 
	quantidade * DEREF(isa.servico).valor AS "valorDoItem",
	CASE DEREF(isa.desconto).valor 
		WHEN 10 THEN '10%' 
		WHEN 20 THEN '20%' 
		WHEN 30 THEN '30%'
		ELSE '0%' 
	END AS "desconto%",
	CASE DEREF(isa.desconto).valor 
		WHEN 10 THEN (quantidade * DEREF(isa.servico).valor * 9/10) 
		WHEN 20 THEN (quantidade * deref(isa.servico).valor * 8/10)  
		WHEN 30 THEN (quantidade * deref(isa.servico).valor * 7/10)  
		ELSE (quantidade * DEREF(isa.servico).valor * 1)  
	END AS valorTotal
FROM
	tb_servicodoatendimento isa
WHERE
	DEREF(isa.atendimento).cod = 1;
-- >>>>> VISUALIZAR O TOTAL GERAL DO ATENDIMENTO E O TOTAL DE CADA SERVICO ATENDIDO
SELECT
	ATEND.COD, ATEND.DATAATENDIMENTO, ATEND.VALORTOTAL, 
	CASE WHEN ((TREAT(DEREF(DEREF(ATEND.CLIENTE).PESSOA) AS TP_FISICA).CPF) IS NOT NULL)
		THEN 'PFISICA-'||(TREAT(DEREF(DEREF(ATEND.CLIENTE).PESSOA) AS TP_FISICA).CPF)
		ELSE 'PJURIDICA-'||(TREAT(DEREF(DEREF(ATEND.CLIENTE).PESSOA) AS TP_JURIDICA).CNPJ)
	END AS CLIENTE,
	ISA.*
FROM
	TB_ATENDIMENTO ATEND
	INNER JOIN TB_SERVICODOATENDIMENTO ISA ON (DEREF(ISA.ATENDIMENTO).COD=ATEND.COD AND ATEND.COD=1);
-- >>>>> VISUALIZAR TODOS OS ITENS REGISTRADOS DO LIVRO 1 QUE ENVOLVEM TIPO DE SERVICO REGISTRO DE FIRMA NO ARQUIVO DO CARTORIO.
SELECT
	LIV.DESCRICAO AS LIVRO, REG.FOLHA AS FOLHA, REG.NUMREGISTRO AS REGISTRO, 
	SERV.DESCRICAO AS SERVICO, TPSERV.DESCRICAO AS TIPO ,ISA.OBSERVACAO
FROM 
	TB_REGISTRO REG, 
	TB_LIVRO LIV,
	TB_SERVICO SERV,
	TB_TIPOSERVICO TPSERV,
	TB_SERVICODOATENDIMENTO ISA
WHERE
	LIV.COD=DEREF(REG.ENVOLVE).COD AND
	deref(reg.envolve).descricao='LIVRO 1' AND 
	DEREF(REG.SERVICODOATENDIMENTO).DATAHORAREALIZACAO=ISA.DATAHORAREALIZACAO AND 
	DEREF(ISA.SERVICO).COD=SERV.COD AND 
	DEREF(SERV.PERTENCE).COD=TPSERV.COD
ORDER BY 
	LIVRO ASC, FOLHA ASC, REGISTRO ASC;

--OBSERVAÇÃO CRIAR UM TRIGGER PARA  GARANTIR QUE ANTES DE INSERIR UM CLIENTE NA TABELA CLIENTE
-- VERIFICAR SE JA EXISTE CLIENTE COM O CPF CADASTRADO SE FOR CLIENTE PESSOA FISICA
-- SENAO SE FOR CLIENTE PESSOA JURIDICA VERIFICAR SE JA EXISTE CLIENTE COM O CNPJ CADASTRADO
-- SE JA EXISTIR CANCELAR A EXECUÇÃO DA OPERAÇÃO DE INSERÇÃO.
--outro trigger quando for realizado a remocao do cliente pessoa fisica ou juridica verificar se ele ja esta registrado como cliente no banco
--se sim nao deixar remover o cliente
-- temos dois problemas galera quando vou excluir a pessoa fisica ou juridica o cliente fica perdido sem referencia
-- era pra nao deixar excluir a pessoa fisica ou juridica.
-- outro problema é quando inserimos um cliente com o mesmo cpf ja cadastrado ele cria um novo cliente
--agora fudeu essa parte aqui pra garantir a integridade referencial visto que a entidade pessoa é nao instatiable nao tem tabela pra
--pessoa so se mudarmos a implementacao e possibilitar a instanciacao de pessoa
-- DEVEMOS GARANTIR A RELACAO ENTRE FUNCIONARIO E PESSOA FISICA 1 PRA 1 VIA TRIGGER
-- POIS DO JEITO QUE TA O FUNCIONARIO DUAS MATRICULAS DISTINTAS PODE SE REFERIR A MESMA PESSOA FISICA
-- E NAO DEVERIA POIS O RELACIONAMENTO É UM PRA UM
-- COMO GARANTIR QUE A RELAÇÃO FUNCIONARIO E PESSOA FISICA SERA UNICA? ACHO QUE SO ATRAVÉS DE TRIGGER