-- CREATE TABLE
CREATE TABLE TB_FISICA OF TP_FISICA (
	COD PRIMARY KEY,
	CPF NOT NULL,
	SEXO NOT NULL CHECK(SEXO IN('M','F')),
	ENDERECO NOT NULL,
	NOME NOT NULL,
	FOTO NULL,
	TELEFONES NULL,     
	CONSTRAINT TB_FISICA_CPFUK UNIQUE(CPF)
 );
CREATE TABLE TB_JURIDICA OF TP_JURIDICA (
	COD PRIMARY KEY,
	CNPJ NOT NULL,
	RAZAOSOCIAL NOT NULL,
	ENDERECO NOT NULL,
	NOME NOT NULL,
	CONSTRAINT TB_JURIDICA_CNPJUK UNIQUE(CNPJ) ,
	CONSTRAINT TB_JURIDICA_RZSOCUK UNIQUE(RAZAOSOCIAL)
);
CREATE TABLE TB_CLIENTE OF TP_CLIENTE (
	COD PRIMARY KEY,
	DATAREGISTRO DEFAULT SYSDATE NOT NULL,
	RENDA NULL,
	REF_CLIENTE NOT NULL
);
CREATE TABLE TB_SETOR OF TP_SETOR (
	COD PRIMARY KEY,
	DESCRICAO NOT NULL,
	CONSTRAINT TB_SETOR_DESCRICAO_UK UNIQUE(DESCRICAO)
);
CREATE TABLE TB_JORNADA OF TP_JORNADA (
	COD PRIMARY KEY,
	DESCRICAO NOT NULL,
	HORAINICIO NOT NULL,
	HORAFIM NOT NULL,
	CONSTRAINT TB_JORNADA_DESCRICAO_UK UNIQUE(DESCRICAO),
	CONSTRAINT TB_JORNADA_HORARIO_UK UNIQUE(HORAINICIO, HORAFIM)
);
CREATE TABLE TB_CARGO OF TP_CARGO (
	COD PRIMARY KEY,
	DESCRICAO NOT NULL,
	CONSTRAINT TB_CARGO_DESCRICAO_UK UNIQUE(DESCRICAO)
);
CREATE TABLE TB_FUNCIONARIO OF TP_FUNCIONARIO (
	MATRICULA PRIMARY KEY,
	DATAADMISSAO DEFAULT SYSDATE NOT NULL,
	SALARIO NOT NULL CHECK (SALARIO >= 788.00),
	STATUS DEFAULT 'A' NOT NULL CHECK(STATUS IN('A','I')), -- A-ATIVO I-INATIVO
	REF_SUPERVISOR NULL SCOPE IS TB_FUNCIONARIO,
	REF_PESSOAFISICA NOT NULL WITH ROWID REFERENCES TB_FISICA, 
	REF_CARGO NOT NULL WITH ROWID REFERENCES TB_CARGO
) NESTED TABLE GRATIFICACOES STORE AS NSTB_GRATIFICACOES ((PRIMARY KEY (NESTED_TABLE_ID, PERIODO)));
CREATE TABLE TB_HISTORICO_SETOR_FUNCIONARIO OF TP_HISTORICO_SETOR_FUNCIONARIO (
	DATAENTRADA DEFAULT SYSTIMESTAMP NOT NULL,
	REF_SETOR NOT NULL WITH ROWID REFERENCES TB_SETOR,
	REF_JORNADA NOT NULL WITH ROWID REFERENCES TB_JORNADA, 
	REF_FUNCIONARIO NOT NULL WITH ROWID REFERENCES TB_FUNCIONARIO,
	PRIMARY KEY(DATAENTRADA)
);
CREATE TABLE TB_TIPOSERVICO OF TP_TIPOSERVICO (
	COD PRIMARY KEY,
	DESCRICAO NOT NULL,
	CONSTRAINT TB_TIPOSERVICO_UK UNIQUE(DESCRICAO)
);
CREATE TABLE TB_SERVICO OF TP_SERVICO( 
	COD PRIMARY KEY,
	DESCRICAO NOT NULL,
	VALOR NOT NULL CHECK(VALOR >= 0.0),
	REF_TIPOSERVICO NOT NULL WITH ROWID REFERENCES TB_TIPOSERVICO,
	CONSTRAINT TB_SERVICO_UK UNIQUE(DESCRICAO)
);
CREATE TABLE TB_DESCONTO OF TP_DESCONTO (
	COD PRIMARY KEY,
	DESCRICAO NOT NULL,
	VALOR NOT NULL CHECK (VALOR >= 0.0),
	CONSTRAINT TB_DESCONTO_DESCUK UNIQUE(DESCRICAO),
	CONSTRAINT TB_DESCONTO_VALORUK UNIQUE(VALOR)
);
CREATE TABLE TB_LIVRO OF TP_LIVRO (
	COD PRIMARY KEY,
	DESCRICAO NOT NULL,
	CONSTRAINT TB_LIVRO_DESCRICAO_UK UNIQUE(DESCRICAO)
);
CREATE TABLE TB_ATENDIMENTO OF TP_ATENDIMENTO (
	COD PRIMARY KEY,
	DATAATENDIMENTO DEFAULT SYSTIMESTAMP NOT NULL,
	VALORTOTAL DEFAULT 0.0 NOT NULL CHECK (VALORTOTAL >= 0.0),
	REF_ATENDENTE NOT NULL WITH ROWID REFERENCES TB_FUNCIONARIO, 
	REF_CLIENTE NOT NULL WITH ROWID REFERENCES TB_CLIENTE
);
CREATE TABLE TB_SERVICODOATENDIMENTO OF TP_SERVICODOATENDIMENTO (
	CODITEM PRIMARY KEY,
	DATAHORAREALIZACAO DEFAULT SYSTIMESTAMP NOT NULL,
	OBSERVACAO NULL,
	QUANTIDADE DEFAULT 1 CHECK (QUANTIDADE >= 1),
	VALORSERVICOREALIZADO DEFAULT 0 CHECK(VALORSERVICOREALIZADO >= 0),
	REF_ATENDIMENTO NOT NULL WITH ROWID REFERENCES TB_ATENDIMENTO, 
	REF_SERVICO NOT NULL WITH ROWID REFERENCES TB_SERVICO, 
	REF_RESPONSAVEL NOT NULL WITH ROWID REFERENCES TB_FUNCIONARIO,
	REF_DESCONTO NULL WITH ROWID REFERENCES TB_DESCONTO
);
CREATE TABLE TB_REGISTRO OF TP_REGISTRO (
	NUMREGISTRO PRIMARY KEY,
	FOLHA NOT NULL CHECK ((FOLHA >= 1) AND (FOLHA <= 200)),
	REF_LIVRO NOT NULL WITH ROWID REFERENCES TB_LIVRO, 
	REF_SERVICODOATENDIMENTO NOT NULL WITH ROWID REFERENCES TB_SERVICODOATENDIMENTO
);
CREATE TABLE TB_LOGATENDIMENTO (
	CODLOG NUMBER NOT NULL,
	DATAOPERACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
	TIPOOPERACAO VARCHAR2(20) NOT NULL,
	USUARIO_BD VARCHAR2(255) NOT NULL,
	TUPLA TP_TUPLAATENDIMENTO NOT NULL,
	CONSTRAINT TB_LOG_LOGATEND_TIPOOPE_CHK CHECK (TIPOOPERACAO IN ('INSER플O','REMO플O','ATUALIZA플O')),
	CONSTRAINT TB_LOG_LOGATEND_PK PRIMARY KEY(CODLOG)
);
CREATE TABLE TB_LOGSERVICODOATENDIMENTO (
	CODLOG NUMBER NOT NULL,
	DATAOPERACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
	TIPOOPERACAO VARCHAR2(20) NOT NULL,
	USUARIO_BD  VARCHAR2(255) NOT NULL,
	TUPLA TP_TUPLASERVICODOATENDIMENTO NOT NULL,
	CONSTRAINT TB_LOG_LOGSERVATEND_TPOP_CHK CHECK (TIPOOPERACAO IN ('INSER플O','REMO플O','ATUALIZA플O')),
	CONSTRAINT TB_LOG_LOGSERVATEND_PK PRIMARY KEY(CODLOG)
);
CREATE TABLE TB_LOGREGISTRO (
	CODLOG NUMBER NOT NULL,
	DATAOPERACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
	TIPOOPERACAO VARCHAR2(20) NOT NULL,
	USUARIO_BD VARCHAR2(255) NOT NULL,
	TUPLA TP_TUPLAREGISTRO NOT NULL,
	CONSTRAINT TB_LOG_LOGREG_TPOP_CHK CHECK (TIPOOPERACAO IN ('INSER플O','REMO플O','ATUALIZA플O')),
	CONSTRAINT TB_LOG_LOGREG_PK PRIMARY KEY(CODLOG)
);