-----------------Comandos de drop para eliminar os elementos do banco de dados do cartório ---------------------------------------------------------------------
/
DROP TABLE "TB_CARGO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_SETOR" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_JORNADA" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_HISTORICO_SETOR_FUNCIONARIO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_ATENDIMENTO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_CLIENTE" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_DESCONTO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_FISICA" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_FUNCIONARIO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_JURIDICA" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_LIVRO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_REGISTRO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_SERVICO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_SERVICODOATENDIMENTO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_TIPOSERVICO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_LOGATENDIMENTO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_LOGSERVICODOATENDIMENTO" CASCADE CONSTRAINTS PURGE;
/
DROP TABLE "TB_LOGREGISTRO" CASCADE CONSTRAINTS PURGE;
/
DROP TYPE "TP_SETOR" FORCE;
/
DROP TYPE "TP_CARGO" FORCE;
/
DROP TYPE "TP_ATENDIMENTO" FORCE;
/
DROP TYPE "TP_CLIENTE" FORCE;
/
DROP TYPE "TP_DESCONTO" FORCE;
/
DROP TYPE "TP_ENDERECO" FORCE;
/
DROP TYPE "TP_FISICA" FORCE;
/
DROP TYPE "TP_TELEFONE" FORCE;
/
DROP TYPE "ARRAY_TELEFONE" FORCE;
/
DROP TYPE "TP_FUNCIONARIO" FORCE;
/
DROP TYPE "TP_GRATIFICACAO" FORCE;
/
DROP TYPE "TP_JURIDICA" FORCE;
/
DROP TYPE "TP_LIVRO" FORCE;
/
DROP TYPE "TP_PESSOA" FORCE;
/
DROP TYPE "TP_REGISTRO" FORCE;
/
DROP TYPE "TP_SERVICO" FORCE;
/
DROP TYPE "TP_SERVICODOATENDIMENTO" FORCE;
/
DROP TYPE "TP_TIPOSERVICO" FORCE;
/
DROP TYPE "TP_TUPLAATENDIMENTO" FORCE;
/
DROP TYPE "TP_TUPLASERVICODOATENDIMENTO" FORCE;
/
DROP TYPE "TP_TUPLAREGISTRO" FORCE;
/
DROP TYPE "NESTED_GRATIFICACAO" FORCE;
/
DROP TYPE "TP_HISTORICO_SETOR_FUNCIONARIO" FORCE;
/
DROP TYPE "TP_JORNADA" FORCE;
/
DROP SEQUENCE "SEQ_PESSOA";
/
DROP SEQUENCE "SEQ_CARGO";
/
DROP SEQUENCE "SEQ_SETOR";
/
DROP SEQUENCE "SEQ_JORNADA";
/
DROP SEQUENCE "SEQ_LIVRO";
/
DROP SEQUENCE "SEQ_TIPOSERVICO";
/
DROP SEQUENCE "SEQ_SERVICO";
/
DROP SEQUENCE "SEQ_DESCONTO";
/
DROP SEQUENCE "SEQ_REGISTRO";
/
DROP SEQUENCE "SEQ_ATENDIMENTO";
/
DROP SEQUENCE "SEQ_SERVICODOATENDIMENTO";
/
DROP FUNCTION "VALIDA_CNPJ";
/
DROP FUNCTION "VALIDA_CPF";
/
DROP DIRECTORY IMAGE_FILES;
/
DROP PROCEDURE "INSERIRPFCOMFOTO";
/
DROP SEQUENCE "SEQ_LOGSERVICODOATENDIMENTO";
/
DROP SEQUENCE "SEQ_LOGATENDIMENTO";
/
DROP SEQUENCE "SEQ_LOGREGISTRO";
/
DROP PACKAGE TRIGGER_API_LOGSERVATEND;
/
