CREATE OR REPLACE TYPE BODY TP_TELEFONE AS
	MEMBER FUNCTION TOSTRING RETURN VARCHAR2 AS RETORNO VARCHAR2(15);
	BEGIN
		SELECT
			SELF.TIPO ||': '||TO_CHAR(SELF.DDD) ||') ' || TO_CHAR(SELF.NUMERO) INTO RETORNO FROM DUAL;
			RETURN RETORNO;
	END TOSTRING;
	MEMBER FUNCTION GETTELEFONE RETURN VARCHAR2 AS RETORNO VARCHAR2(15);
	BEGIN
		SELECT
			'('||TO_CHAR(SELF.DDD) ||') ' || TO_CHAR(SELF.NUMERO) INTO RETORNO FROM DUAL;
			RETURN RETORNO;
	END GETTELEFONE;
END;