CREATE OR REPLACE TYPE BODY TP_PESSOA AS
	MEMBER FUNCTION GETENDERECO RETURN VARCHAR2 AS RETORNO VARCHAR2(550);
	BEGIN
		SELECT
			'LOGRADOURO: '||SELF.ENDERECO.LOGRADOURO ||
			' Nº ' || TO_CHAR(SELF.ENDERECO.NUMERO)||
			' BAIRRO: ' || SELF.ENDERECO.BAIRRO||
			' CIDADE: '|| SELF.ENDERECO.CIDADE ||'-'||SELF.ENDERECO.UF||
			' CEP: '||SELF.ENDERECO.CEP INTO RETORNO FROM DUAL;
			RETURN RETORNO;
	END GETENDERECO;
	MEMBER FUNCTION GETFONES RETURN VARCHAR2 AS RETORNO VARCHAR2(55);
	BEGIN
		IF(SELF.TELEFONES IS NOT NULL) THEN
			RETORNO:='';
			FOR I IN 1..SELF.TELEFONES.COUNT
			LOOP
				RETORNO := RETORNO||SELF.TELEFONES(I).GETTELEFONE||' ';
			END LOOP;
		ELSE
			RETORNO := 'NENHUM';
		END IF;
		RETURN RETORNO;
	END GETFONES;
	MEMBER FUNCTION GETINFO RETURN VARCHAR2 AS RETORNO VARCHAR2(15);
	BEGIN
		SELECT
			' COD: '||TO_CHAR(SELF.COD)||
			' NOME: '||TO_CHAR(SELF.NOME)||
			' ENDEREÇO: '||SELF.GETENDERECO()||
			' FONES: '||SELF.GETFONES() INTO RETORNO FROM DUAL;
		RETURN RETORNO;
	END GETINFO;
	MAP MEMBER FUNCTION GETCOD RETURN NUMBER AS
	BEGIN
		RETURN SELF.COD;
	END GETCOD;
	STATIC FUNCTION COMPARE(OBJ1 TP_PESSOA, OBJ2 TP_PESSOA) RETURN BOOLEAN AS RESULTADO BOOLEAN;
	BEGIN
		RESULTADO := FALSE;
		IF (OBJ1.COD = OBJ2.COD) THEN
			RESULTADO := TRUE;
		END IF;
		RETURN RESULTADO;
	END COMPARE;
END;