CREATE OR REPLACE TYPE BODY TP_CARGO AS 
	MEMBER FUNCTION GETINFO RETURN VARCHAR2 AS RETORNO VARCHAR2(855);
	BEGIN
		SELECT
			' CÓDIGO DO CARGO: ' || TO_CHAR(SELF.COD) ||
			' DESCRICAO: ' || (SELF.DESCRICAO)
			INTO RETORNO FROM DUAL;
		RETURN RETORNO;
	END GETINFO;
	ORDER MEMBER FUNCTION EQUALS(OBJ TP_CARGO) RETURN NUMBER AS
	BEGIN
		RETURN (SELF.COD - OBJ.COD); -- ZERO: SELF > OBJ | NEGATIVO: SELF < OBJ | POSITIVO: SELF > OBJ
	END EQUALS;
	STATIC FUNCTION COMPARE(OBJ1 TP_CARGO, OBJ2 TP_CARGO) RETURN BOOLEAN AS RETORNO BOOLEAN;
	BEGIN
		RETORNO:=FALSE;
		IF (TO_CHAR(OBJ1.COD) = TO_CHAR(OBJ2.COD) OR (OBJ1.DESCRICAO=OBJ2.DESCRICAO)) THEN
			RETORNO:=TRUE;
		ELSE
			RETORNO:=FALSE;
		END IF;
		RETURN RETORNO;
	END COMPARE;
	CONSTRUCTOR FUNCTION TP_CARGO(DESCRICAO IN VARCHAR2) RETURN SELF AS RESULT AS
	BEGIN
		SELF.COD := SEQ_CARGO.NEXTVAL;
		SELF.DESCRICAO := DESCRICAO;
		RETURN;
	END TP_CARGO;
END;