CREATE OR REPLACE TYPE BODY TP_SETOR AS
	MEMBER FUNCTION GETINFO RETURN VARCHAR2 AS RETORNO VARCHAR2(855);
	BEGIN
		SELECT
			' CÓDIGO DO SETOR: ' || TO_CHAR(SELF.COD) ||
			' DESCRIÇÃO: ' || (SELF.DESCRICAO)
			INTO RETORNO FROM DUAL;
			RETURN RETORNO;
	END GETINFO;
	ORDER MEMBER FUNCTION EQUALS(OBJ TP_SETOR) RETURN NUMBER AS
	BEGIN
		RETURN (SELF.COD - OBJ.COD); -- ZERO: SELF > OBJ | NEGATIVO: SELF < OBJ | POSITIVO: SELF > OBJ
	END EQUALS;
	STATIC FUNCTION COMPARE(OBJ1 TP_SETOR, OBJ2 TP_SETOR) RETURN BOOLEAN AS RETORNO BOOLEAN;
	BEGIN
		RETORNO := FALSE;
		IF (TO_CHAR(OBJ1.COD) = TO_CHAR(OBJ2.COD) OR (OBJ1.DESCRICAO=OBJ2.DESCRICAO)) THEN
			RETORNO := TRUE;
		ELSE
			RETORNO := FALSE;
		END IF;
		RETURN RETORNO;
	END COMPARE;
	CONSTRUCTOR FUNCTION TP_SETOR(DESCRICAO IN VARCHAR2) RETURN SELF AS RESULT AS
	BEGIN
		SELF.COD := SEQ_SETOR.NEXTVAL;
		SELF.DESCRICAO := DESCRICAO;
		RETURN;
	END TP_SETOR;
END;