CREATE OR REPLACE TYPE BODY TP_JORNADA AS MEMBER FUNCTION GETINFO RETURN VARCHAR2 AS RETORNO VARCHAR2(855);
	BEGIN
		SELECT
		' CÓDIGO DO JORNADA: ' || TO_CHAR(SELF.COD) ||
		' DESCRIÇÃO: ' || (SELF.DESCRICAO) ||
		' HORÁRIO INICIO: ' || TO_CHAR((SELF.HORAINICIO), 'HH24:MI:SS')||
		' HORÁRIO FIM: ' || TO_CHAR((SELF.HORAFIM), 'HH24:MI:SS')
		INTO RETORNO FROM DUAL;
		RETURN RETORNO;
	END GETINFO;
	ORDER MEMBER FUNCTION EQUALS(OBJ TP_JORNADA) RETURN NUMBER AS
	BEGIN
		RETURN (SELF.COD - OBJ.COD); -- ZERO: SELF > OBJ | NEGATIVO: SELF < OBJ | POSITIVO: SELF > OBJ
	END EQUALS;
	STATIC FUNCTION COMPARE(OBJ1 TP_JORNADA, OBJ2 TP_JORNADA) RETURN BOOLEAN AS RETORNO BOOLEAN;
	BEGIN
		RETORNO:=FALSE;
	IF(TO_CHAR(OBJ1.COD) = TO_CHAR(OBJ2.COD) OR (OBJ1.DESCRICAO=OBJ2.DESCRICAO)) THEN
		RETORNO:=TRUE;
	ELSE
		RETORNO:=FALSE;
	END IF;
	RETURN RETORNO;
	END COMPARE;
	CONSTRUCTOR FUNCTION TP_JORNADA(DESCRICAO IN VARCHAR2, HORAINICIO IN INTERVAL DAY TO SECOND, HORAFIM IN INTERVAL DAY TO SECOND) RETURN SELF AS RESULT AS
	BEGIN
			SELF.COD := SEQ_JORNADA.NEXTVAL;
			SELF.DESCRICAO := DESCRICAO;
			SELF.HORAINICIO := HORAINICIO;
			SELF.HORAFIM := HORAFIM);
		RETURN;
	END TP_JORNADA;
END;