-- CREATE FUNCTION
CREATE OR REPLACE FUNCTION VALIDA_CPF(CPF VARCHAR2 ) RETURN VARCHAR2 IS
	V_CPF_NUMBER VARCHAR2(14) := REGEXP_REPLACE(CPF, '[^0-9]');
	CPF_C NUMBER := LPAD(V_CPF_NUMBER,11,'0');
	TAM NUMBER(2) := LENGTH(SUBSTR(V_CPF_NUMBER,-2,2));
	TOT1 NUMBER(4) := 0;
	TOT2 NUMBER(4) := 0;
	MULTIPLICADOR NUMBER(2) := 9;
	DIGITO NUMBER(1) := 0;
	RESTO1 NUMBER(2) := 0;
	RESTO2 NUMBER(2) := 0;
	DC1_CPF NUMBER(1) := 0;
	DC2_CPF NUMBER(1) := 0;
	DIGITO_DIG CHAR(2) := SUBSTR(V_CPF_NUMBER,-2,2);
	CPF_X NUMBER := SUBSTR(LPAD(TO_CHAR(CPF_C),11,'0'),1,9);
	TAMANHO NUMBER(2) := LENGTH(TO_CHAR(CPF_X));
	DC_CPF CHAR(2);
BEGIN
	FOR I IN REVERSE 1..TAMANHO
	LOOP
		TOT1 := TOT1 + MULTIPLICADOR * (SUBSTR(TO_CHAR(CPF_X),I,1));
		MULTIPLICADOR := MULTIPLICADOR - 1;
	END LOOP;
	RESTO1 := MOD(TOT1,11);
	IF RESTO1 = 10 THEN
		DC1_CPF := 0;
	ELSE
		DC1_CPF := RESTO1;
	END IF;
	DIGITO := DC1_CPF;
	TOT2 := TOT2 + 9 * DIGITO;
	MULTIPLICADOR := 8;
	FOR I IN REVERSE 1..TAMANHO
	LOOP
		TOT2 := TOT2 + MULTIPLICADOR * (SUBSTR(TO_CHAR(CPF_X),I,1));
		MULTIPLICADOR := MULTIPLICADOR - 1;
	END LOOP;
	RESTO2 := MOD(TOT2,11);
	IF RESTO2 = 10 THEN
		DC2_CPF := 0;
	ELSE
		DC2_CPF := RESTO2;
	END IF;
	DC_CPF := TO_CHAR(DC1_CPF) || TO_CHAR(DC2_CPF);
	IF DC_CPF = DIGITO_DIG THEN
		RETURN 'SIM';
	ELSE
		RETURN 'NÃO';
	END IF;
END VALIDA_CPF;